import cv2
img=cv2.imread(r"C:\Users\HP\Downloads\my_photo.jpg")
gr=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#cv2.imshow('original image',img)
#cv2.imshow('original image',gr)
invert=cv2.bitwise_not(gr)
cv2.imshow('original image',invert)
blur=cv2.GaussianBlur(invert,(21,21),0)
invertedblur=cv2.bitwise_not(blur)
sketch=cv2.divide(gr,invertedblur,scale=256.0)
cv2.imshow('original image',img)
cv2.imshow('sketch image',sketch)
cv2.waitKey(0)
